# Generated by Django 2.1.15 on 2021-01-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='markup',
        ),
        migrations.AddField(
            model_name='productoption',
            name='markuprate',
            field=models.IntegerField(blank=True, default=35, null=True, verbose_name='Mark-Up Rate'),
        ),
        migrations.AlterField(
            model_name='domesticproduct',
            name='markup',
            field=models.IntegerField(blank=True, default=35, null=True, verbose_name='Mark Up Rate(in %)'),
        ),
    ]
