# Generated by Django 2.1.15 on 2021-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210104_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimportsitem',
            name='forex',
            field=models.FloatField(blank=True, null=True, verbose_name='Forex'),
        ),
        migrations.AddField(
            model_name='importsproduct',
            name='forex',
            field=models.FloatField(blank=True, default=1.35, null=True, verbose_name='Forex'),
        ),
    ]
