# Generated by Django 3.1.4 on 2020-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201210_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_number', models.CharField(max_length=250)),
                ('prduct_cost', models.ManyToManyField(to='core.Price')),
            ],
        ),
    ]
