# Generated by Django 3.1.4 on 2020-12-10 10:22

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0005_auto_20201210_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'managed': True, 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'managed': True, 'verbose_name': 'Quantity', 'verbose_name_plural': 'Quantities'},
        ),
        migrations.AlterModelTable(
            name='price',
            table='tbl_price',
        ),
        migrations.AlterModelTable(
            name='quantity',
            table='tbl_quantity',
        ),
    ]
