# Generated by Django 3.1.4 on 2020-12-10 10:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0006_auto_20201210_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcost',
            options={'managed': True, 'verbose_name': 'Product Cost', 'verbose_name_plural': 'Product Costs'},
        ),
        migrations.AlterModelTable(
            name='productcost',
            table='tbl_productCost',
        ),
    ]
