# Generated by Django 3.1.4 on 2020-12-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201211_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcost',
            old_name='get_prduct_cost',
            new_name='get_product_cost',
        ),
        migrations.RenameField(
            model_name='productcost',
            old_name='prduct_cost',
            new_name='product_cost',
        ),
    ]
