# Generated by Django 3.1.4 on 2020-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201211_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcost',
            name='test_cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
