# Generated by Django 3.1.4 on 2020-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productcost_test_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcost',
            name='product_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcost',
            name='test_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
