# Generated by Django 3.1.4 on 2020-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201211_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cost', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
