# Generated by Django 3.1.4 on 2020-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='option_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
