# Generated by Django 3.1.4 on 2020-12-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productoption_option_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markup',
            field=models.CharField(blank=True, help_text='Mark Up Value in Dollar($).', max_length=250, null=True),
        ),
    ]
