# Generated by Django 3.1.4 on 2020-12-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_markup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySortableClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'My Sortable Class',
                'verbose_name_plural': 'My Sortable Classes',
                'ordering': ['the_order'],
            },
        ),
    ]
