# Generated by Django 3.1.4 on 2020-12-21 06:31

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0004_mysortableclass'),
        
    ]

    operations = [
        migrations.DeleteModel(
            name='MySortableClass',
        ),
        migrations.AlterModelTable(
            name='quantity',
            table='tbl_qunatity',
        ),
    ]
