# Generated by Django 3.1.4 on 2020-12-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201221_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(help_text='Price in Dollar($).', max_length=30),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(max_length=30),
        ),
    ]
