# Generated by Django 3.1.4 on 2020-12-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201221_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(help_text='Price in Dollar($).'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
