# Generated by Django 3.1.4 on 2020-12-23 09:39

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True, 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelTable(
            name='region',
            table='tbl_region',
        ),
    ]
