# Generated by Django 3.1.4 on 2020-12-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201223_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup',
            field=models.IntegerField(blank=True, default=35, null=True, verbose_name='Mark Up(in %)'),
        ),
    ]
