# Generated by Django 3.1.4 on 2020-12-29 05:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0003_auto_20201223_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'Domestic Product', 'verbose_name_plural': 'Domestic Products'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='tbl_dproduct',
        ),
    ]
