# Generated by Django 3.1.4 on 2020-12-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201229_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'managed': True, 'verbose_name': 'Products Options', 'verbose_name_plural': 'Products Options'},
        ),
    ]
