# Generated by Django 3.1.4 on 2020-12-29 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201229_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=250, null=True)),
                ('productname', models.CharField(blank=True, max_length=250, null=True)),
                ('markup', models.IntegerField(blank=True, default=35, null=True, verbose_name='Mark Up(in %)')),
                ('productcostc', models.FloatField(blank=True, null=True, verbose_name='Product Cost C$')),
                ('targetgrossprofit', models.FloatField(blank=True, null=True, verbose_name='Target Gross Profit (in%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
                ('subcatagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subcategory')),
                ('subsubcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subsubcategory')),
            ],
            options={
                'verbose_name': 'Import Product',
                'verbose_name_plural': 'Imports Products',
                'db_table': 'tbl_iproduct',
                'managed': True,
            },
        ),
    ]
