# Generated by Django 3.1.4 on 2020-12-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_importsproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddItem',
            new_name='AddDomesticItem',
        ),
        migrations.AlterModelOptions(
            name='adddomesticitem',
            options={'managed': True, 'verbose_name': 'Domestic Item', 'verbose_name_plural': 'Domestic Items'},
        ),
        migrations.AddField(
            model_name='importsproduct',
            name='setupfee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='adddomesticitem',
            table='tbl_domesticitems',
        ),
        migrations.CreateModel(
            name='AddImportsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('productcost', models.FloatField(blank=True, null=True, verbose_name='Product Cost C$')),
                ('baseproductsalesprice', models.FloatField(blank=True, null=True, verbose_name='Base Product Sales Price C$')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Imports Item',
                'verbose_name_plural': 'Imports Items',
                'db_table': 'tbl_importsitems',
                'managed': True,
            },
        ),
    ]
