# Generated by Django 3.1.4 on 2020-12-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_adddomesticitem_setupfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddomesticitem',
            name='setupfee',
        ),
        migrations.AddField(
            model_name='addimportsitem',
            name='setupfee',
            field=models.FloatField(blank=True, null=True, verbose_name='Setup Fee'),
        ),
    ]
