# Generated by Django 3.1.4 on 2020-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201229_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addimportsitem',
            name='baseproductsalesprice',
            field=models.FloatField(blank=True, null=True, verbose_name='Base Product Sales Price U$'),
        ),
        migrations.AlterField(
            model_name='addimportsitem',
            name='productcost',
            field=models.FloatField(blank=True, null=True, verbose_name='Product Cost U$'),
        ),
        migrations.AlterField(
            model_name='importsproduct',
            name='productcostc',
            field=models.FloatField(blank=True, null=True, verbose_name='Product Cost U$'),
        ),
        migrations.AlterField(
            model_name='importsproduct',
            name='targetgrossprofit',
            field=models.FloatField(blank=True, null=True, verbose_name='Target Gross Profit (in %)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='targetgrossprofit',
            field=models.FloatField(blank=True, default=33, null=True, verbose_name='Target Gross Profit (in %)'),
        ),
    ]
