# Generated by Django 3.1.4 on 2020-12-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201229_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importsproduct',
            old_name='productcostc',
            new_name='productcostu',
        ),
    ]
