# Generated by Django 3.1.4 on 2020-12-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201229_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimportsitem',
            name='netduty',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Duty U$'),
        ),
        migrations.AddField(
            model_name='importsproduct',
            name='duty',
            field=models.IntegerField(blank=True, default=18, null=True, verbose_name='Duty (in %)'),
        ),
        migrations.AddField(
            model_name='importsproduct',
            name='markuprate',
            field=models.IntegerField(blank=True, default=15, null=True, verbose_name='Mark Up Rate(in %)'),
        ),
        migrations.AlterField(
            model_name='importsproduct',
            name='markup',
            field=models.IntegerField(blank=True, default=15, null=True, verbose_name='Markup (in %)'),
        ),
    ]
