# Generated by Django 3.1.4 on 2020-12-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201229_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsproduct',
            name='markuprate',
            field=models.IntegerField(blank=True, default=35, null=True, verbose_name='Mark Up Rate(in %)'),
        ),
    ]
