# Generated by Django 3.1.4 on 2020-12-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201229_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimportsitem',
            name='duty',
            field=models.FloatField(blank=True, null=True, verbose_name='Duty (in %)'),
        ),
        migrations.AddField(
            model_name='addimportsitem',
            name='markup',
            field=models.FloatField(blank=True, null=True, verbose_name='Markup'),
        ),
    ]
